# This workflow will deploy the sphinx document.

name: sphinx-deploy-gh-pages

on:
  push:
    branches: [ "devel-doc" ]

jobs:
  sphinx-build:
    runs-on: ubuntu-latest
    steps:
    - name: Install and Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install python dependencies
      run: pip install sphinx sphinx-rtd-theme

    - name: Checkout the project repository
      uses: actions/checkout@v2

    - name: Build the sphinx document.
      working-directory: doc
      run: |
        make html

    - name: Deploy the sphinx document.
      working-directory: doc
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/html
